title: Site

tabs:
  articles:
    label: Articles
    sections:
      baa_articles:
        type: pages
        headline: Baa Articles
        parent: site.find("baa")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 3/6
          author:
            label: Author
            type: users
            query: page.author
            text: "{{ user.name }}"
            width: 1/6
          category:
            label: Category
            text: "{{ page.category }}"
            width: 1/6
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/6
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/6
        sortBy: date desc
        create:
          template: article
        empty: "No BAA articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category

      Archives_articles:
        type: pages
        headline: Archives Entries
        parent: site.find("archives")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 3/6
          author:
            label: Author
            type: users
            query: page.author
            text: "{{ user.name }}"
            width: 1/6
          category:
            label: Category
            text: "{{ page.category }}"
            width: 1/6
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/6
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/6
        sortBy: date desc
        create:
          template: article
        empty: "No history articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category

      gallery_articles:
        type: pages
        headline: Gallery Articles
        parent: site.find("gallery")
        template: article
        layout: table
        columns:
          title:
            label: Title
            width: 3/6
          author:
            label: Author
            type: users
            query: page.author
            text: "{{ user.name }}"
            width: 1/6
          category:
            label: Category
            text: "{{ page.category }}"
            width: 1/6
          created:
            label: Created
            type: date
            value: "{{ page.date }}"
            width: 1/6
          status:
            label: Status
            text: "{{ page.status }}"
            width: 1/6
        sortBy: date desc
        create:
          template: article
        empty: "No gallery articles yet. Create your first article!"
        search: true
        filters:
          - status
          - category

      # earth_articles:
      #   type: pages
      #   headline: Earth Articles
      #   parent: site.find("earth")
      #   template: article
      #   layout: table
      #   columns:
      #     title:
      #       label: Title
      #       width: 3/6
      #     author:
      #       label: Author
      #       type: users
      #       query: page.author
      #       text: "{{ user.name }}"
      #       width: 1/6
      #     category:
      #       label: Category
      #       text: "{{ page.category }}"
      #       width: 1/6
      #     created:
      #       label: Created
      #       type: date
      #       value: "{{ page.date }}"
      #       width: 1/6
      #     status:
      #       label: Status
      #       text: "{{ page.status }}"
      #       width: 1/6
      #   sortBy: date desc
      #   create:
      #     template: article
      #   empty: "No earth articles yet. Create your first article!"
      #   search: true
      #   filters:
      #     - status
      #     - category

  pages:
    label: Pages
    sections:
      pages:
        type: pages
        headline: Pages
        layout: pages
        sortBy: num asc
        template:
          - blog
          - blocks
        create:
          - blog
          - blocks
        columns:
          title:
            label: Title
            width: 2/3
          template:
            label: Template
            text: "{{ page.intendedTemplate }}"
            width: 1/3


      tech:
        type: pages
        headline: Tech Pages
        layout: pages
        sortBy: num asc
        templatesIgnore:
          - blog
          - blocks
          - article
        columns:
          title:
            label: Title
            width: 2/3
          template:
            label: Template
            text: "{{ page.intendedTemplate }}"
            width: 1/3

