version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Beirut
      - WEBUI_PORT=8080
    volumes:
      - ./config/qb:/config
      - ./downloads:/downloads
      - ./media:/media
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Beirut
      - PLEX_CLAIM=
    volumes:
      - ./config/plex:/config
      - ./media:/media
    ports:
      - "32400:32400"
    restart: unless-stopped
